plugins:
  - jekyll-remote-theme
  
  
# theme: jekyll-theme-minimal
remote_theme: benbalter/retlab
title: Ben Blaukopf's Portfolio

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false
